const Router = require("express")
const router = new Router()
const authMiddleware = require('../middleware/auth.middleware')
const musicController = require('../controllers/musicController')

router.post('',authMiddleware,musicController.createMusicDir)
router.post('/upload',authMiddleware,musicController.uploadMusic)
router.post('/comments',authMiddleware, musicController.addCommentMusic)
router.post('',authMiddleware,musicController.fetchMusics)
router.patch('/edit/:id',authMiddleware,musicController.editMusic)
router.get('',authMiddleware,musicController.fetchMusics)
router.get('/like',authMiddleware,musicController.likeMusic)
router.get('/play',authMiddleware, musicController.playMusic)
router.get('/musicPage/:id',authMiddleware, musicController.getMusic)
router.get('/download',authMiddleware,musicController.downloadMusic)
router.get('/search',authMiddleware,musicController.searchMusic)
router.get('/musicPage/:id',authMiddleware,musicController.findAuthorById)
router.get('/getAuthor',authMiddleware,musicController.findAuthorById)
router.get("/comments",authMiddleware,musicController.getComments)
router.get("/recommends",authMiddleware,musicController.getRecommendMusic)
router.get("/recommends/search",authMiddleware,musicController.searchRecommendMusic)
router.get("/profile/:id",authMiddleware,musicController.getMusicsProfile)
router.get("/search/profile",authMiddleware,musicController.searchProfileMusic)
router.delete('/',authMiddleware,musicController.deleteMusic)

module.exports=router